### ISSUE TITLE
Shadowenv triggers errors with pipes

### ISSUE THREAD

**Issue by Morriar** [Shopify/shadowenv#20]
Hi there,

When I'm using pipes in the command line such as:

```bash
echo "foo" | wc
```

I get:

```bash
-bash: child setpgid (3238 to 3232): Operation not permitted
```

(but the command actually works)

I tried with an empty `.bash_profile` and `.bashrc` no problem.
I also tried with `zsh` and `sh`, no problem.

This only occurs when I'm loading `dev.sh` from my `.bashrc` in `Terminal` or `ITerm2`.
More specifically, if I comment the `eval "$(/usr/local/bin/shadowenv init "${__shellname}")"`, the problem disappears.

Config:

```bash
$ system_profiler SPSoftwareDataType
    System Software Overview:

      System Version: macOS 10.14.2 (18C54)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

$ bash --version
GNU bash, version 5.0.0(1)-release (x86_64-apple-darwin17.7.0)

$ sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

$ zsh --version
5.3 (x86_64-apple-darwin18.0)
```

Here the content of my `.bashrc` file:

```bash
if [[ -f /opt/dev/dev.sh ]] && [[ $- == *i* ]]; then
  source /opt/dev/dev.sh
fi
```

And the problem occurs with an empty `.bash_profile`.

Any idea?

**Comment by burke** [comment]
Could you show the output of `echo $BASH_VERSION` ?

**Comment by Morriar** [comment]
Here it is:

```bash
$ echo $BASH_VERSION
5.0.0(1)-release
```

**Comment by burke** [comment]
Huh, too bad. I'll look into it today.

**Comment by burke** [comment]
```
dev update-hookbook > bash
👩‍💻  activated ruby:2.3.7
activated shadowenv.
bash-5.0$ echo|wc
       1       0       1
bash-5.0$
```

Should be fixed now if you `dev update` -- please give it a shot and report back!

**Comment by burke** [comment]
Ah, perhaps not with shadowenv yet. A little later on today at most.

**Comment by burke** [comment]
Ok, should be fixed now.

**Comment by Morriar** [comment]
I did the `dev update` but I still have the problem.

```bash
$ dev update
👩‍💻  checking for updates... done!
$ echo "foo" | wc
-bash: child setpgid (17101 to 17095): Operation not permitted
       1       1       4
```

Also tried with a new term, a re-source config and a reboot.

Am I missing something?

**Comment by Morriar** [comment]
Same thing within a new bash:

```bash
$ bash
👩‍💻  activated ruby:2.5.3
bash-5.0$ echo foo | cat
bash: child setpgid (17430 to 17424): Operation not permitted
foo
```

**Comment by burke** [comment]
Hm, I think you may have to `dev up` somewhere to force it to update to `shadowenv 0.2.1` and then restart your shell as well.

**Comment by Morriar** [comment]
Yup, I needed to `dep up` also:

```bash
$ dev update
👩‍💻  checking for updates... done!
$ dev up
┏━━ 👩‍💻  1/3 Global System Setup ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✓ installing shadowenv 0.2.1
┃ 𝒾 EJSON pre-commit hook
┃ ✓ EJSON pre-commit hook: done
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (1.64s) ━━
⭑ 2/3 Ruby
⭑ 3/3 Bundler
$ echo "foo" | cat
foo
```

No more error :)

Thank you very much!
